# Generated by Django 4.0.4 on 2022-10-08 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='account',
            new_name='acc',
        ),
    ]
