# Generated by Django 4.0.4 on 2022-10-08 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_rename_account_followers_acc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='account',
            new_name='acc',
        ),
    ]
