# Generated by Django 4.0.4 on 2022-11-22 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_followers_id_alter_following_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='followpfk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='network.post'),
            preserve_default=False,
        ),
    ]
