# Generated by Django 4.0.4 on 2022-11-22 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_following_followpfk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='followpfk',
        ),
    ]
